scripts/install_deps.sh

Fix install-deps

---

contracts/Bridge.sol
test/chainBridge/createDepositProposal.js
test/chainBridge/depositGeneric.js
test/chainBridge/voteDepositProposal.js

- Merging changes made in [ChainBridgeV2 PR 260](https://github.com/ChainSafe/ChainBridgeV2/pull/260)

Merge changes from PR 260

---

test/chainBridge/voteDepositProposal.js

Added this as a sanity check, might as well keep it.
- Adds execution test

Add execution test

---

test/chainBridge/depositERC721.js
test/chainBridge/depositGeneric.js
test/chainBridge/voteDepositProposal.js

- quick test fix to update what we prepend the variable length part of our constructed data with

Test fix: Specify length of bytes in terms of number of bytes

---

contracts/handlers/ERC20Handler.sol
test/chainBridge/depositERC20.js
test/e2eERC20.js

- No longer pad addresses, bytes containing addresses are exactly as long as the address

non-padded addresses

---

contracts/Bridge.sol
contracts/handlers/ERC20Handler.sol
test/e2eERC20.js

- adds len of recipient address to deposit record

added length of recipientAddress to deposit record

---

contracts/Bridge.sol
test/chainBridge/depositCentrifugeAsset.js
test/chainBridge/depositERC20.js
test/chainBridge/depositERC721.js
test/chainBridge/depositGeneric.js

- Indexes nonce (required for internal message)
- Removes source chain Id (this is implicitly provided)
- Adds erc20 test to confirm nonce change

Update deposit event

---

scripts/cli/cmd/deploy.js

- Displays cost in ether of deloyment
- Add logs for each contract so user can watch progress

Adds cost output to deploy

---

contracts/ERC20Safe.sol

- Add fund method for erc20Handler

Add erc20 fund method

---

test/contractBridge/voteDepositProposal.js

Needed to verify for my own sanity, end up refactoring as it was in need of some love.
- Updates vote tests to use 4 relayers with a threshold of 3

Update vote tests

---

.travis.yml
contracts/handlers/ERC721Handler.sol
scripts/cli/cmd/erc721.js

Enable ERC721 cmds on travis

---

contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
test/e2e/erc721/erc721SameChain.js

- FIx assembly parsing of recipient address
- Check deposit record in tests

Extend erc721 tests

---

contracts/handlers/CentrifugeAssetHandler.sol

After our conversation @ansermino here is the event that the client listens to. Until the fully generic handler is set up.
Creating PR for the new bindings as well.

Adding Centrifuge Asset Stored Event

---

contracts/handlers/ERC721Handler.sol

- Use resource ID for token address instead of (?)

ERC721: Use resource ID for token address

---

contracts/handlers/GenericHandler.sol
test/contractBridge/depositGeneric.js
test/handlers/generic/deposit.js
test/handlers/generic/executeDeposit.js

- Remove recipient from generic handler data
- Remove function sig from passed in data, appended inside contract instead

Simplify generic handler

---

README.md
cli/cmd/bridge.js
cli/cmd/centrifuge.js
cli/cmd/deploy.js
cli/cmd/index.js
cli/cmd/utils.js
cli/constants.js
cli/index.js
scripts/ci_cli.sh

- Adds `register-generic-resource`
- Re-enables centrifuge, uses new asset store contract (`cent getHash`)

Updates generic and centrifuge cmds

---

contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
contracts/handlers/GenericHandler.sol
test/e2e/erc721/erc721SameChain.js
test/handlers/generic/deposit.js

- Use double mapping with dest ID

Store deposit records by destination ID

---

contracts/Bridge.sol
contracts/CentrifugeAsset.sol
contracts/TestContracts.sol
contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
contracts/handlers/GenericHandler.sol
contracts/handlers/HandlerHelpers.sol

- Update various `public` methods to `external`
- Update ERC20, ERC721, and Generic handler assembly to use `calldataload` instead of `mload`

Reduce Gas Usage - Method Accessibility

---

cli/cmd/erc20.js
cli/cmd/erc721.js
contracts/Bridge.sol
contracts/handlers/ERC721Handler.sol
test/contractBridge/admin.js
test/contractBridge/createDepositProposal.js
test/contractBridge/depositERC20.js
test/contractBridge/depositERC721.js
test/contractBridge/depositGeneric.js
test/contractBridge/fee.js
test/contractBridge/voteDepositProposal.js
test/e2e/erc20/differentChainsMock.js
test/e2e/erc20/sameChain.js
test/e2e/erc721/differentChainsMock.js
test/e2e/erc721/sameChain.js
test/handlers/erc20/deposit.js
test/handlers/erc20/depositBurn.js
test/handlers/erc721/burnList.js
test/handlers/erc721/deposit.js
test/handlers/erc721/depositBurn.js
test/handlers/generic/constructor.js
test/handlers/generic/deposit.js
test/handlers/generic/executeDeposit.js
test/helpers.js

- Add `_resourceIDToHandlerAddress` mapping to Bridge.sol
- Update `deposit`, `voteProposal`, and `executeProposal` to use new mapping
- Update tests accordingly

ResouceID to Handler Address Mapping

---

test/e2e/erc721/sameChain.js
test/gasBenchmarks/deployments.js
test/gasBenchmarks/deposits.js
test/gasBenchmarks/executeProposal.js
test/gasBenchmarks/voteProposal.js
test/handlers/erc20/constructor.js
test/handlers/erc20/deposit.js
test/handlers/generic/executeDeposit.js

- Add gas benchmark tests for:
- contract deployments
- deposits
- create/vote proposals
- execute proposals

Gas Benchmarks

---

contracts/ERC20Safe.sol
contracts/ERC721Safe.sol

- Added conditional in both safes to verify that the recipient address is the address of our current contract

Fix _balances do not represent contract balance as it should (4.9 – medium)

---

contracts/Bridge.sol
test/contractBridge/voteDepositProposal.js

- Update `voteProposal` method to check provided `dataHash` against the `dataHash` submitted when proposal was created

Add datahash check

---

contracts/Bridge.sol

- Change state before call to external contract

Fix theoretical Re-entrancy attack on executeProposal function (4.3 – critical)

---

contracts/handlers/HandlerHelpers.sol

Fix setResource can be simplified (4.12 – minor) 

---

README.md
cli/cmd/bridge.js
cli/cmd/deploy.js
cli/cmd/erc20.js
cli/cmd/erc721.js
cli/cmd/utils.js
cli/index.js
scripts/ci_cli.sh
scripts/geth/run_geth.sh

- Adds `--gas-limit` and `--gas-price` options

CLI gas options

---

contracts/ERC20Safe.sol
contracts/ERC721Safe.sol

- Create safe transfers for each token.

Fix Transfer functions of ERC20 tokens may return false (4.2 – critical)

---

contracts/Bridge.sol
contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
contracts/handlers/GenericHandler.sol
contracts/interfaces/IDepositExecute.sol
test/handlers/generic/constructor.js
test/handlers/generic/executeProposal.js

- Rename instances of executeDeposit to executeProposal

Rename instances of executeDeposit to executeProposal

---

cli/cmd/admin.js
cli/cmd/bridge.js
cli/cmd/centrifuge.js
cli/cmd/erc20.js
cli/cmd/erc721.js
cli/cmd/index.js
cli/cmd/utils.js
cli/docs/admin.md
cli/docs/docs.md
cli/index.js
scripts/ci_cli.sh

- Adds `admin` sub-command and several sub-sub-commands
- Adds `log` function to make output more consistent
-

More admin commands

---

contracts/ERC721Safe.sol

- made erroneous assumption erc721 transferFrom would return boolean.

Remove ERC721 safeTransferFrom

---

contracts/Bridge.sol
contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
contracts/handlers/GenericHandler.sol
contracts/interfaces/IDepositExecute.sol
test/contractBridge/cancelDepositProposal.js
test/contractBridge/createDepositProposal.js
test/contractBridge/depositERC20.js
test/contractBridge/depositERC721.js
test/contractBridge/depositGeneric.js
test/contractBridge/fee.js
test/contractBridge/voteDepositProposal.js
test/e2e/erc20/differentChainsMock.js
test/e2e/erc20/sameChain.js
test/e2e/erc721/differentChainsMock.js
test/e2e/erc721/sameChain.js
test/gasBenchmarks/deposits.js
test/gasBenchmarks/executeProposal.js
test/gasBenchmarks/voteProposal.js
test/handlers/erc20/deposit.js
test/handlers/erc20/depositBurn.js
test/handlers/erc721/deposit.js
test/handlers/erc721/depositBurn.js
test/handlers/generic/deposit.js
test/handlers/generic/executeProposal.js
test/helpers.js

- remove resourceID from calldata for all handlers
- update all the tests

remove resource id from calldata

---

contracts/Bridge.sol
test/contractBridge/cancelDepositProposal.js

- Require proposal not to be cancelled when cancelling

Don't cancel if already cancelled

---

contracts/handlers/HandlerHelpers.sol

- Removed createResourceID from handler helpers
- tests were already updated

removed extraneous function from handler helpers

---

contracts/handlers/ERC20Handler.sol

- Change ERC20Handler typo in assembly, thanks to @lastperson for pointing it out!

Fix ERC20Handler Typo

---

contracts/Bridge.sol

- Fix typo on Bridge contract title comment.

Typo on Contract title comment

---

contracts/Bridge.sol
contracts/ERC1155Safe.sol
contracts/handlers/ERC1155Handler.sol
contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
contracts/handlers/HandlerHelpers.sol
contracts/interfaces/IERCHandler.sol
test/contractBridge/admin.js
test/contractBridge/depositERC1155.js
test/e2e/erc1155/differentChainsMock.js
test/e2e/erc1155/sameChain.js
test/gasBenchmarks/executeProposal.js
test/helpers.js

Add ERC1155Handler.
Closes: #407<issue>

add erc1155Handler, erc1155Safe, and modify HandlerHelpers

---

test/contractBridge/depositERC1155.js
test/e2e/erc1155/sameChain.js
test/gasBenchmarks/deployments.js
test/gasBenchmarks/deposits.js
test/handlers/erc1155/burnList.js
test/handlers/erc1155/deposit.js
test/handlers/erc1155/depositBurn.js
test/helpers.js

add remaining tests for erc1155

---

contracts/ERC20Safe.sol
test/handlers/erc20/deposit.js

Add a check if the token address is a contract in erc20 handler.
Closes: #<issue>

check if the token address is a contract in erc20 handler

---

package.json

Relase new version, includes:
- updated dependencies
- added bridge and handlers typings and ABIs to release

Relase v2.1.0

---

.github/workflows/publish-contracts.yml

Add missing step to publish package to github registry

Fix publishing package

---

package.json

Release 2.1.1.

---

.github/workflows/publish-contracts.yml
package.json

- publish to npm regsitry
- create types for all contracts in GH action

Publish to npm registry

---

package.json

release v2.1.3 to npm registry

Release v2.1.3 to npm

---

package.json

Release contracts Release v3.0.1

Release v3.0.1

---

contracts/Bridge.sol

Fix Bridge descriptions after access segregation

Fix Bridge descriptions after access segregation

---

package.json

release 3.1.0

---

contracts/ERC721Safe.sol
contracts/handlers/ERC721Handler.sol
test/handlers/erc721/depositBurn.js

Closes: Sygma-09
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ x] I have added tests to cover my changes.

Fix burn from not owner

---

contracts/handlers/GenericHandler.sol
contracts/handlers/HandlerHelpers.sol

Fix `setResource` function description
Closes: chainsafe/sygma#121

Fix `setResource` function description
